version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    container_name: ex-mongo
    environment:
      MONGO_INITDB_DATABASE: ex-mongo
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: